# Generated by Django 4.1.7 on 2023-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=16)),
                ('response_tone', models.CharField(choices=[('Professional', 'Professional'), ('Helpful', 'Helpful'), ('Friendly', 'Friendly'), ('Direct', 'Direct'), ('Academic', 'Academic')], max_length=12)),
                ('design_requirements', models.TextField()),
            ],
        ),
    ]
