# Generated by Django 4.1.7 on 2023-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(default='\n# Enter your code here\n'),
        ),
    ]
