# Generated by Django 4.1.7 on 2023-10-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_starter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='allow_new_tabs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='tabs',
            field=models.JSONField(default=list),
        ),
    ]
