# Generated by Django 4.1.7 on 2023-11-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_tabs_alter_problem_starter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
