# Generated by Django 4.1.7 on 2023-11-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problemtest_name_alter_problem_design_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_code',
        ),
    ]
