# Generated by Django 4.1.7 on 2023-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_remove_problem_language_problem_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('code', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='languages',
        ),
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=models.ManyToManyField(to='problems.legallanguage'),
        ),
    ]
