# Generated by Django 4.1.7 on 2023-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_legallanguage_remove_problem_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legallanguage',
            name='runnable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
