# Generated by Django 4.1.7 on 2023-11-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_legallanguage_runnable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legallanguage',
            options={'verbose_name': 'language'},
        ),
    ]
